### PR TITLE
nan: upgrade to 2.x (with iojs support)

### PR DESCRIPTION
**Pull request by gierschv**

### CODE REVIEW

**Comment by gierschv** [comment]
It seems that mocha 2.3 uses *lodash.create* "^3.1.1" which doesn't work with node 0.8.x: @TooTallNate  do you prefer to drop the CI with node 0.8.x or force mocha to < 2.3?

Also the compilation with iojs 3.3.0, fails in travis with a lot of errors but I don't have this issue when building node-lame locally with this version.

**Comment by TooTallNate** [comment]
We can keep v0.8 compat in Travis by using a script like this one: https://github.com/TooTallNate/ref/blob/bbda46d4e19a88513d4f1ac2aee2ce1606bb11f3/.travis.yml

**Comment by gierschv** [comment]
@TooTallNate Ok, added.

**Comment by TooTallNate** [comment]
You're gonna want the other _cruft_ in that file for things to build properly. nan requires a C++11 compiler so we have to update Travis' default one otherwise iojs 3.2+ will fail to compile.

**Comment by gierschv** [comment]
@TooTallNate Thanks for the tips, that's much better now :)

**Comment by TooTallNate** [comment]
Thanks!

**Pull request merged**
